export const types={
    groupUrl: 'dashboard',
    groupName: 'Qonteo',
    groupId: '12169343',
    authChecking:'[auth] Checking login state',
    authCheckingFinish: '[auth] Finish Checking login state',
    authStartLogin: '[auth] Start login',
    authLogin: '[auth] Login',
    authStartRegister: '[auth] Start Register',
    authLogout: '[auth] Logout',

    dataVehicles: '[vehicles] inicialize data',
    setHoursVehicles:'[Vehicles] Change grafic hours',
    setWeeksVehicles:'[Vehicles] Change grafic Week',
    setMonthsVehicles:'[Vehicles] Change grafic Month',

    dataPersons: '[Persons] inicialize data',
    getMapHeat:'[Person Grafic] get HeatMap',
 
    setHoursPersons:'[Persons] change grafic hours Total',
    setHoursPersonsMale:'[Persons] change grafic hours male',
    setHoursPersonsFemale:'[Persons] change grafic hours female',
    setWeekPersons:'[Persons] Change grafic Week total',
    setWeekPersonsMale:'[Persons] Change grafic Week male',
    setWeekPersonsFemale:'[Persons] Change grafic Week female',
    setMonthGraficPersons:'[Persons] Change grafic Month total',
    setMonthGraficPersonsMale:'[Persons] Change grafic Month male',
    setMonthGraficPersonsFemale:'[Persons] Change grafic Month female',
    setGraficRangesAges:'[Persons] Change grafic Age Ranges',
    changeDate:'[Date] set New Date',

    setDateStartHourVehicle:'[Date] change date start hour vehicle',
    setDateEndHourVehicle:'[Date] change date End hour vehicle',
    setDateStartWeekVehicle:'[Date] change date start Week vehicle',
    setDateEndWeekVehicle:'[Date] change date End Week vehicle',
    setDateStartMonthVehicle:'[Date] change date start Month vehicle',
    setDateEndMonthVehicle:'[Date] change date End Month vehicle',

    setDateStartHourPerson:'[Date] change date start hour Person',
    setDateEndHourPerson:'[Date] change date End hour Person',
    setDateStartHourMalePerson:'[Date] change date start hour Male Person',
    setDateEndHourMalePerson:'[Date] change date End hour Male Person',
    setDateStartHourFemalePerson:'[Date] change date start hour Female Person',
    setDateEndHourFemalePerson:'[Date] change date End hour Female Person',
    setDateStartWeekPerson:'[Date] change date start Week Person',
    setDateEndWeekPerson:'[Date] change date End Week Person',
    setDateStartWeekMalePerson:'[Date] change date start Week Male Person',
    setDateEndWeekMalePerson:'[Date] change date End Week Male Person',
    setDateStartWeekFemalePerson:'[Date] change date start Week Female Person',
    setDateEndWeekFemalePerson:'[Date] change date End Week Female Person',
    setDateStartMonthPerson:'[Date] change date start Month Person',
    setDateEndMonthPerson:'[Date] change date End Month Male Person',
    setDateStartMonthMalePerson:'[Date] change date start Month Male Person',
    setDateEndMonthMalePerson:'[Date] change date End Month Person',
    setDateStartMonthFemalePerson:'[Date] change date start Month Female Person',
    setDateEndMonthFemalePerson:'[Date] change date End Month Female Person',
    setDateStartAgePerson:'[Date] change date start Age Person',
    setDateEndAgePerson:'[Date] change date End Age Person',
    setDateStartPlate:'[Date] change date start Plate',
    setDateEndPlate:'[Date] change date End Plate',
    
    uiMenu: '[UI] Menu',
    uiMenuHide: '[UI] Menu Hide',

    getPlate:'[Plate] get plate',
    startLoadingPlate:'[Plate] start loading',
    searchPlate:'[Plate] search Plate',
    sortByPlate:'[Plate] Sort By PLate',
    sortByDate:'[Plate] Sort By Date',
    sortByHour:'[Plate] Sort By Hour',
    sortByLocation:'[Plate] Sort By Location',
    sortByTimes:'[Plate] Sort By Times',
    sortByClient:'[Plate] Sort By Client',
    sortByMembership:'[Plate] Sort by Menbership',
    setPlatesCurrenDate:'[Plate] Set Date Plate',

    dataTypeVehicle:'[Type Vehicle] Init Data'
}